# Generated by Django 4.1.6 on 2023-02-12 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 11, 33, 31, 878166, tzinfo=datetime.timezone.utc)),
        ),
    ]
